services:
  api:
    build:
        context: .
        dockerfile: ./DockerAPI/Dockerfile
    image: api:latest
    container_name: api
    ports:
      - "1234:5000"
  
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    container_name: database
    environment:
      - ACCEPT_EULA=true
      - MSSQL_SA_PASSWORD=Test@123
    ports:
      - "1433:1433"
  
  database-seed:
    depends_on:
      - database
    build:
        context: ./DockerAPI/DB
        dockerfile: ./Dockerfile
    container_name: database-seed
   